-- MySQL Script generated by MySQL Workbench
-- 2018年05月01日 星期二 18时28分27秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zhiyu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zhiyu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zhiyu` DEFAULT CHARACTER SET utf8 ;
USE `zhiyu` ;

-- -----------------------------------------------------
-- Table `zhiyu`.`publish_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zhiyu`.`publish_category` (
  `id` INT NOT NULL,
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '发布信息类别（类别ID,类别名称）';


-- -----------------------------------------------------
-- Table `zhiyu`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zhiyu`.`Users` (
  `id` CHAR(32) NOT NULL,
  `account` VARCHAR(45) NULL,
  `pwd` VARCHAR(45) NULL,
  `gender` VARCHAR(2) NULL,
  `age` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `zhiyu`.`publish_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zhiyu`.`publish_item` (
  `id` CHAR(32) NOT NULL,
  `publisher` CHAR(32) NULL,
  `infocate` INT NULL,
  `site` VARCHAR(45) NULL,
  `actiontime` VARCHAR(45) NULL,
  `detail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `infocate_idx` (`infocate` ASC),
  INDEX `publisher_idx` (`publisher` ASC),
  CONSTRAINT `publisher`
    FOREIGN KEY (`publisher`)
    REFERENCES `zhiyu`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `infocate`
    FOREIGN KEY (`infocate`)
    REFERENCES `zhiyu`.`publish_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zhiyu`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zhiyu`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `zhiyu`.`response_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zhiyu`.`response_item` (
  `id` CHAR(32) NOT NULL,
  `responser` CHAR(32) NULL,
  `publishid` CHAR(32) NULL,
  `responsedetail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `responser_idx` (`responser` ASC),
  INDEX `publishid_idx` (`publishid` ASC),
  CONSTRAINT `responser`
    FOREIGN KEY (`responser`)
    REFERENCES `zhiyu`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `publishid`
    FOREIGN KEY (`publishid`)
    REFERENCES `zhiyu`.`publish_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
